### ISSUE TITLE
Feedstock out of date.

### ISSUE THREAD

**Issue by utf** [conda-forge/amset-feedstock#18]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi @jan-janssen, this feedstock is out of date. You're listed as the maintainer for this repo, are you able to update it?

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by jan-janssen** [comment]
There was an issue with the dependencies of the package, you can read more about the issue in the first pul request https://github.com/conda-forge/amset-feedstock/pull/14 - I triggered a rebuild and put it on the list for next weekend.

**Comment by utf** [comment]
Great, thanks for the info. 

I just released a new version of amset, so it would be great if we could get this onto conda.

The new version has relaxed the constraints on the dependency versions, so hopefully it should be easy to fix.

**Comment by jan-janssen** [comment]
With the latest version I get the error message: 
```
ImportError: cannot import name 'desym' from 'amset.tools.desym' 
```

**Comment by utf** [comment]
I've just pushed a new version (0.4.17) that should fix that issue.

**Comment by jan-janssen** [comment]
I merged the new version, it should be available after approximately 2 hours.

**Comment by utf** [comment]
Fantastic, thanks very much.

**Comment by jan-janssen** [comment]
Btw. If you want to I can add you as a maintainer as well
